application: poll-chart
version: 94481
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  login: required
  script: admin.py


- url: /polls/persist
  login: admin
  script: main.py

- url: .*
  script: main.py
